/**
 * Monte Carlo balance harness (GDD §20 / brief §8).
 *
 *   npm run simulate -- --runs 2000 --tiers 1-8 --policies naive,greedy,optimal
 *
 * Plays full 27-hole tour runs per tier per policy with reduceInPlace (no
 * cloning) and reports against the GDD's health targets. Writes BALANCE.md.
 */
import { writeFileSync } from 'node:fs'
import {
  initRound,
  reduceInPlace,
  policyAction,
  seedStream,
  SUNNYVALE_RUN,
  tierConfig,
  TIERS,
  type PolicyName,
  type SimState,
} from '../src/sim/index'

interface Args {
  runs: number
  tiers: number[]
  policies: PolicyName[]
  cut1: number | null
  cut2: number | null
}

function parseArgs(argv: string[]): Args {
  let runs = 500
  let tiers = [1, 2, 3, 4, 5, 6, 7, 8]
  let policies: PolicyName[] = ['naive', 'greedy', 'optimal']
  let cut1: number | null = null
  let cut2: number | null = null
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--runs') runs = Number(argv[++i])
    if (argv[i] === '--tiers') {
      const spec = argv[++i]!
      tiers = spec.includes('-')
        ? (() => {
            const [a, b] = spec.split('-').map(Number)
            return Array.from({ length: b! - a! + 1 }, (_, k) => a! + k)
          })()
        : spec.split(',').map(Number)
    }
    if (argv[i] === '--policies') policies = argv[++i]!.split(',') as PolicyName[]
    if (argv[i] === '--cut1') cut1 = Number(argv[++i])
    if (argv[i] === '--cut2') cut2 = Number(argv[++i])
  }
  return { runs, tiers, policies, cut1, cut2 }
}

interface CellStats {
  runs: number
  wins: number
  missedCut1: number
  missedCut2: number
  deckDead: number
  holeDiffs: Map<number, number>
  totalHoles: number
  finalStrokes: number[]
  actionsPerRun: number[]
  reshuffles: number
}

function emptyStats(): CellStats {
  return {
    runs: 0,
    wins: 0,
    missedCut1: 0,
    missedCut2: 0,
    deckDead: 0,
    holeDiffs: new Map(),
    totalHoles: 0,
    finalStrokes: [],
    actionsPerRun: [],
    reshuffles: 0,
  }
}

function median(xs: number[]): number {
  if (xs.length === 0) return 0
  const s = [...xs].sort((a, b) => a - b)
  return s[Math.floor(s.length / 2)]!
}

function pct(n: number, d: number): string {
  return d === 0 ? '—' : `${((100 * n) / d).toFixed(1)}%`
}

function playRun(tier: number, policy: PolicyName, seed: string, stats: CellStats): void {
  const config = tierConfig(tier)
  if (args.cut1 !== null) config.cuts[0]!.maxToPar = args.cut1
  if (args.cut2 !== null) config.cuts[1]!.maxToPar = args.cut2
  let st: SimState = initRound(seed, SUNNYVALE_RUN, config)
  const rng = seedStream(seed, `policy-${policy}`)
  let actions = 0
  while (st.phase !== 'runComplete' && actions < 900) {
    st = reduceInPlace(st, policyAction(st, policy, rng))
    actions++
    if (st.lastEvents.some((e) => e.includes('reshuffled') || e.includes('Lucky Penny'))) {
      stats.reshuffles++
    }
  }
  stats.runs++
  stats.actionsPerRun.push(actions)
  if (st.runEnd === 'complete') {
    stats.wins++
    stats.finalStrokes.push(st.scores.reduce((a, b) => a + b, 0))
  } else if (st.runEnd === 'deckDead') {
    stats.deckDead++
  } else if (st.scores.length <= 9) {
    stats.missedCut1++
  } else {
    stats.missedCut2++
  }
  st.scores.forEach((s, i) => {
    const diff = s - st.holes[i]!.par
    stats.holeDiffs.set(diff, (stats.holeDiffs.get(diff) ?? 0) + 1)
    stats.totalHoles++
  })
}

const args = parseArgs(process.argv.slice(2))
const { runs, tiers, policies } = args
const t0 = Date.now()
const results = new Map<string, CellStats>()

for (const tier of tiers) {
  for (const policy of policies) {
    const stats = emptyStats()
    for (let i = 0; i < runs; i++) {
      playRun(tier, policy, `mc-${tier}-${policy}-${i}`, stats)
    }
    results.set(`${tier}:${policy}`, stats)
    const elapsed = ((Date.now() - t0) / 1000).toFixed(0)
    console.log(
      `tier ${tier} ${policy.padEnd(7)} win ${pct(stats.wins, stats.runs).padStart(6)}  ` +
        `cut1✗ ${pct(stats.missedCut1, stats.runs).padStart(6)}  ` +
        `cut2✗ ${pct(stats.missedCut2, stats.runs).padStart(6)}  ` +
        `deckDead ${pct(stats.deckDead, stats.runs).padStart(6)}  [${elapsed}s]`,
    )
  }
}

function diffPct(stats: CellStats, pred: (d: number) => boolean): string {
  let n = 0
  for (const [d, c] of stats.holeDiffs) if (pred(d)) n += c
  return pct(n, stats.totalHoles)
}

// ---- report ---------------------------------------------------------------

const lines: string[] = []
lines.push('# BALANCE.md — Monte Carlo report')
lines.push('')
lines.push(`Generated by \`tools/simulate.ts\`: **${runs} runs** × tiers {${tiers.join(', ')}} × policies {${policies.join(', ')}} on the Sunnyvale 27-hole tour run. Policies use no clubs yet (club-inclusion metrics land with the M5 content pass).`)
lines.push('')
lines.push('## Win rates (complete all 27 holes)')
lines.push('')
lines.push(`| Tier | ${policies.map((p) => p).join(' | ')} |`)
lines.push(`|---|${policies.map(() => '---:').join('|')}|`)
for (const tier of tiers) {
  const row = policies.map((p) => {
    const s = results.get(`${tier}:${p}`)!
    return pct(s.wins, s.runs)
  })
  lines.push(`| ${tier} ${TIERS[tier - 1]!.name} | ${row.join(' | ')} |`)
}
lines.push('')
lines.push('## Where runs die / per-hole scoring (optimal policy)')
lines.push('')
lines.push('| Tier | miss cut 1 | miss cut 2 | deck dead | median strokes (wins) | median actions | est. minutes | birdie+ | par | double+ |')
lines.push('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|')
for (const tier of tiers) {
  const s = results.get(`${tier}:optimal`)
  if (!s) continue
  const estMin = ((median(s.actionsPerRun) * 5.5) / 60).toFixed(1)
  lines.push(
    `| ${tier} | ${pct(s.missedCut1, s.runs)} | ${pct(s.missedCut2, s.runs)} | ${pct(s.deckDead, s.runs)} | ${median(s.finalStrokes) || '—'} | ${median(s.actionsPerRun)} | ${estMin} | ${diffPct(s, (d) => d < 0)} | ${diffPct(s, (d) => d === 0)} | ${diffPct(s, (d) => d >= 2)} |`,
  )
}
lines.push('')
lines.push('## Health targets (GDD §20)')
lines.push('')
const o1 = results.get('1:optimal')
const o8 = results.get('8:optimal')
const g1 = results.get('1:greedy')
const n1 = results.get('1:naive')
function verdict(ok: boolean): string {
  return ok ? '✅' : '❌'
}
if (o1 && n1 && g1) {
  const o1w = o1.wins / o1.runs
  const g1w = g1.wins / g1.runs
  const n1w = n1.wins / n1.runs
  lines.push('| Metric | Target | Measured | Verdict |')
  lines.push('|---|---|---|---|')
  lines.push(`| Optimal-ish win rate, Tier 1 | 55–65% | ${pct(o1.wins, o1.runs)} | ${verdict(o1w >= 0.55 && o1w <= 0.65)} |`)
  if (o8) {
    const o8w = o8.wins / o8.runs
    lines.push(`| Optimal-ish win rate, Tier 8 | 8–15% | ${pct(o8.wins, o8.runs)} | ${verdict(o8w >= 0.08 && o8w <= 0.15)} |`)
  }
  lines.push(`| Greedy vs Optimal gap, Tier 1 | ≥ 20 pts | ${((o1w - g1w) * 100).toFixed(1)} pts | ${verdict(o1w - g1w >= 0.2)} |`)
  lines.push(`| Naive win rate, Tier 1 | < 15% | ${pct(n1.wins, n1.runs)} | ${verdict(n1w < 0.15)} |`)
  const par1 = (() => {
    let n = 0
    for (const [d, c] of o1.holeDiffs) if (d === 0) n += c
    return n / o1.totalHoles
  })()
  const birdie1 = (() => {
    let n = 0
    for (const [d, c] of o1.holeDiffs) if (d < 0) n += c
    return n / o1.totalHoles
  })()
  const dbl1 = (() => {
    let n = 0
    for (const [d, c] of o1.holeDiffs) if (d >= 2) n += c
    return n / o1.totalHoles
  })()
  lines.push(`| Par modal, Tier 1 (optimal) | par most common | par ${(par1 * 100).toFixed(1)}%, birdies ${(birdie1 * 100).toFixed(1)}%, doubles+ ${(dbl1 * 100).toFixed(1)}% | ${verdict(par1 >= birdie1 && par1 >= dbl1)} |`)
  lines.push(`| Birdie rate ~18%, Tier 1 | 12–24% | ${(birdie1 * 100).toFixed(1)}% | ${verdict(birdie1 >= 0.12 && birdie1 <= 0.24)} |`)
  lines.push(`| Doubles+ ~12%, Tier 1 | 6–18% | ${(dbl1 * 100).toFixed(1)}% | ${verdict(dbl1 >= 0.06 && dbl1 <= 0.18)} |`)
}
lines.push('')
lines.push(`_Total simulated: ${[...results.values()].reduce((a, s) => a + s.runs, 0)} runs in ${((Date.now() - t0) / 1000).toFixed(0)}s._`)
lines.push('')

writeFileSync('BALANCE.md', lines.join('\n'))
console.log('\nwrote BALANCE.md')
